### ISSUE TITLE
Transformers Tests Tracker

### ISSUE THREAD

**Issue by edenlightning** [Lightning-Universe/lightning-transformers#59]
## Task Smoke Tests  #33

- [x] lightning_transformer/task/huggingface/language_modeling
- [x] lightning_transformer/task/huggingface/multiple_choice
- [ ] lightning_transformer/task/huggingface/question_answering
- [x] lightning_transformer/task/huggingface/summarization
- [x] lightning_transformer/task/huggingface/text_classification
- [x] lightning_transformer/task/huggingface/token_classification
- [x] lightning_transformer/task/huggingface/translation
- [ ] train.py (related: #34)

## unittests (minimal tests)

- [ ] lightning_transformer/core
- [ ] lightning_transformer/huggingface
- [ ] lightning_transformer/huggingface/seq2seq
- [ ] lightning_transformer/task/huggingface/language_modeling
- [ ] lightning_transformer/task/huggingface/multiple_choice
- [ ] lightning_transformer/task/huggingface/question_answering
- [ ] lightning_transformer/task/huggingface/summarization
- [ ] lightning_transformer/task/huggingface/text_classification
- [ ] lightning_transformer/task/huggingface/token_classification
- [ ] lightning_transformer/task/huggingface/translation

## Others

- [ ] Clean-up CI
- [ ] Format codebase
- [ ] Run pre-commit in CI
- [ ] Clean-up requirements
